server:
  port: 8112
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mall4j-mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mall4j_cbec_b2c}?allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 0
      maximum-pool-size: 20
      idle-timeout: 25000
      auto-commit: true
      connection-test-query: select 1
  data:
    redis:
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}

logging:
  config: classpath:logback/logback-docker.xml
  # 接受异常通知的邮箱
  log-error-email: ${LOG_ERROR_EMAIL:}
  # 当前环境，比如测试环境，生产环境
  log-env: ${LOG_ENV:}
